package com.vaadin.designer.springnavigation;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.v7.ui.HorizontalLayout;
import com.vaadin.v7.ui.Label;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainLayoutDesign extends HorizontalLayout {
	protected HorizontalLayout menuTitle;
	protected Label menuTitleLabel;
	protected Button menuToggle;
	protected CssLayout menuItems;
	protected Button userButton;
	protected Button statusButton;
	protected Button inboxButton;
	protected Button archiveButton;
	protected Button settingsButton;
	protected Button logoutButton;

	public MainLayoutDesign() {
		Design.read(this);
	}
}
